spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
          - id: card-service-route
            uri: lb://CARDSERVICE
            predicates:
            - Path=/api/bankapp/cards/**
            filters:
            - RewritePath=/api/bankapp/cards(?<segment>.*), /api/cards${segment}   
server:
  port: 30723

eureka:
  instance:
    prefer-ip-address: true
  client: 
    service-url:
      defaultZone: http://localhost:8080/eureka
